* Moldable Emacs
:PROPERTIES:
:CREATED:  [2021-06-18 Fri 21:45]
:ID:       db0f9ac1-54f7-476e-b566-0a8395e9943c
:END:

This is an extension of Emacs aiming to enable Moldable Development.
Or better still, aiming to make you a better story teller when you
deal with code.

TODO: I will detail dependencies and more information in a later change.

*Ah! This is a pretty alpha release: I have a plan for quite few
changes ahead! So avoid to build upon this prototype for now!!*


** Installation
:PROPERTIES:
:CREATED:  [2021-06-23 Wed 00:09]
:ID:       b68dfda8-54d1-498c-b6f1-fdc52eb21889
:END:

The suggested way to install this package is via [[https://github.com/jwiegley/use-package][use-package]]. This is
my installation configuration:

#+begin_src elisp :noeval
(use-package moldable-emacs
  :init (if (f-directory-p "~/.emacs.d/lisp/moldable-emacs")
            (shell-command "cd ~/.emacs.d/lisp/moldable-emacs; git pull;")
          (shell-command "cd ~/.emacs.d/lisp/; git clone git@github.com:ag91/moldable-emacs.git"))
  :load-path "~/.emacs.d/lisp/moldable-emacs/"
  :bind (("C-c m m" . me-mold)
         ("C-c m f" . me-go-forward)
         ("C-c m b" . me-go-back)
         ("C-c m o" . me-open-at-point)
         ("C-c m d" . me-mold-docs)
         ("C-c m e a" . me-mold-add-last-example)
         )
  :config
  (require 'moldable-emacs)
  (add-to-list 'me-files-with-molds (concat (file-name-directory (symbol-file 'me-mold)) "molds/experiments.el")) ;; TODO this is relevant only if you have private molds
  (me-setup-molds))
#+end_src

If you are using =Doom Emacs= slightly modify this:

#+begin_src elisp :noeval
(use-package! moldable-emacs
  ...
  (me-setup-molds))
(add-load-path! "~/.emacs.d/lisp/moldable-emacs/molds")
#+end_src

I am working on making =moldable-emacs= itself explain which optional
and external dependencies you may need for what, but it is still work
in progress. For now an incomplete list from the top of my mind.


*** Emacs Dependencies
:PROPERTIES:
:CREATED:  [2021-06-23 Wed 00:10]
:END:

This package requires:

- dash.el
- s.el
- async.el
- thunk.el


Optionally:

- emacs-tree-sitter.el

  you can get more functionality if you install tree-sitter's grammars
  as well.
- esxml.el
- code-compass.el
- org-ql
- ... (check these via the mold "WhatMoldsCanIUse?")


*** TODO (Optional) External Dependencies
:PROPERTIES:
:CREATED:  [2021-06-23 Wed 00:15]
:END:

- graph-cli
- graphviz
- imgclip
- ???

*** Testing

Install the [[https://github.com/doublep/eldev][Elisp Development Tool (Eldev)]] and run

#+begin_src shell
  eldev test
#+end_src


** Tutorials
:PROPERTIES:
:CREATED:  [2021-10-04 Mon 21:40]
:ID:       ed317af9-902e-4048-a74f-035ce8af58bf
:END:

You should be able to access tutorials via the "Show Tutorials" mold.
Or you can look in [[tutorials/]].

** Further info
:PROPERTIES:
:CREATED:  [2021-06-18 Fri 21:51]
:END:

*** View code duplication as an Org buffer
:PROPERTIES:
:CREATED:  [2021-06-18 Fri 21:52]
:ID:       449520e9-de3b-48f9-8f06-bc1f6437102c
:END:

https://ag91.github.io/blog/2021/05/26/moldable-emacs-make-everything-moldable-through-lisp

*** Vision
:PROPERTIES:
:CREATED:  [2021-06-18 Fri 21:51]
:ID:       dc37968c-16b8-4414-b51d-77b245162970
:END:

https://ag91.github.io/blog/2021/06/18/moldable-emacs-vision-basic-concepts-and-design
*** Exploring JSON via Elisp
:PROPERTIES:
:CREATED:  [2021-06-18 Fri 21:51]
:ID:       8a0e46f3-4407-4851-a440-f0994367b4b4
:END:

https://ag91.github.io/blog/2021/06/18/moldable-emacs-how-to-explore-json-via-elisp
*** [Setup] Clojure tree-sitter grammar installation
:PROPERTIES:
:CREATED:  [2021-06-23 Wed 00:20]
:ID:       751a4e84-5193-4dbb-9fc9-91ec7a14c6b4
:END:

https://ag91.github.io/blog/2021/06/22/how-(simple-is)-to-install-a-clojure-tree-sitter-grammar-and-use-it-from-emacs/
*** OCR mold
:PROPERTIES:
:CREATED:  [2021-07-19 Mon 19:37]
:ID:       dede04d1-b6c9-43c8-b3f4-d968fb89991b
:END:

https://ag91.github.io/blog/2021/07/16/moldable-emacs-capturing-text-from-open-images-with-an-ocr-mold
*** Grabbing hyperlinks from HTML with Playground
:PROPERTIES:
:CREATED:  [2021-07-19 Mon 19:38]
:ID:       6796b283-eca9-498a-bf25-0451f5832a03
:END:

https://ag91.github.io/blog/2021/07/19/moldable-emacs-capture-links-from-html-with-playground/
*** Showing examples for a Clojure function at point
:PROPERTIES:
:CREATED:  [2021-07-27 Tue 23:21]
:ID:       646f46fd-6a78-4c23-bccc-28fe51be76e7
:END:

https://ag91.github.io/blog/2021/07/27/moldable-emacs-finding-examples-of-clojure-functions-(with-tests)/
*** Code transformation: edit your CSS files with a Playground!
:PROPERTIES:
:CREATED:  [2021-08-11 Wed 22:14]
:ID:       9f3ab44c-8b79-41ed-bc57-183614f32eaa
:END:

https://ag91.github.io/blog/2021/08/11/moldable-emacs-editing-your-file-via-treesitter-(or-how-i-fixed-my-css-with-a-playground)/
*** Prototype: integrating Nyxt and Vega-Lite
:PROPERTIES:
:CREATED:  [2021-09-22 Wed 23:42]
:END:

https://ag91.github.io/blog/2021/08/22/moldable-emacs-vega-lite-nyxt-and-emacs-towards-sustainable-development

*** Taking notes with molds
:PROPERTIES:
:CREATED:  [2021-09-22 Wed 23:42]
:END:

https://ag91.github.io/blog/2021/09/05/moldable-emacs-taking-lispy-notes-that-are-easier-to-search

*** Howto: Migrating to a terser format for molds
:PROPERTIES:
:CREATED:  [2021-09-22 Wed 00:05]
:ID:       2763024c-15ef-49da-bf94-888ec3de95e2
:END:

https://ag91.github.io/blog/2021/09/19/moldable-emacs-making-molds-a-little-easier-to-write/

*** Extend molds via hooks
:PROPERTIES:
:CREATED:  [2021-09-24 Fri 23:51]
:ID:       dfb3ceec-80f1-4d73-abf4-7a31ec422d86
:END:

https://ag91.github.io/blog/2021/09/23/moldable-emacs-extending-the-playground-powers-via-hooks-to-include-dired

*** Check which molds you can use and demo them!
:PROPERTIES:
:CREATED:  [2021-10-02 Sat 01:55]
:ID:       65d29893-3b52-47ec-a1c7-aa5b47f893e7
:END:

https://ag91.github.io/blog/2021/10/02/moldable-emacs-molds-need-examples-too/

*** Moldable tutorials
:PROPERTIES:
:CREATED:  [2021-10-16 Sat 00:10]
:ID:       b19d6408-4b54-4736-961c-ea7a1ffcf9f2
:END:

https://ag91.github.io/blog/2021/10/15/moldable-emacs-moldable-tutorials/

*** Stats mold
:PROPERTIES:
:CREATED:  [2021-10-30 Sat 16:16]
:END:

https://ag91.github.io/blog/2021/10/22/moldable-emacs-how-to-get-useful-info-about-a-buffer-without-reading-it/

*** JavaScript and Parenscript Mold with Nyxt
:PROPERTIES:
:CREATED:  [2021-10-30 Sat 16:17]
:ID:       04a7d91a-b061-4800-ae91-01309b0f58f7
:END:

https://ag91.github.io/blog/2021/10/29/emacs-with-nyxt-capturing-youtube-links-at-time-and-molding-nyxt-with-js/
